services:
  app:
    image: ghcr.io/ciffelia/koe:latest
    init: true
    depends_on:
      redis:
        condition: service_started
      voicevox:
        condition: service_healthy
    restart: unless-stopped
    env_file: ./config/.env

  redis:
    image: redis:7.0.2
    command: /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "redis-data:/data"

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-0.12.2
    restart: unless-stopped
    healthcheck:
      test: wget --tries=1 -O - http://localhost:50021/version || exit 1
      interval: 5s
      timeout: 10s
    expose:
      - 50021
    volumes:
      - "./config/voicevox_presets.yaml:/opt/voicevox_engine/presets.yaml:ro"

volumes:
  redis-data:
