services:
  app:
    image: "ghcr.io/ciffelia/koe:latest"
    init: true
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    env_file: ./config/.env
    volumes:
      - "./secret:/home/koe/secret:ro"

  redis:
    image: "redis:6.2.6"
    command: /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 4
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf:ro"
      - "redis-data:/data"

volumes:
  redis-data:
