[package]
name = "koe-speech"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
koe-audio = { path = "../koe-audio" }
anyhow = "1"
tokio = "1"
google-texttospeech1 = "2"
hyper = "0.14"
hyper-rustls = "0.22"
yup-oauth2 = "5"
base64 = "0.13"
