[package]
name = "koe-speech"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
koe-audio = { path = "../koe-audio" }
anyhow = { version = "1", features = ["backtrace"] }
url = "2"
reqwest = "0.11"
