[package]
name = "koe-config"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
serde = { version = "1", features = ["derive"] }
envy = "0.4"
