name: Publish release

on: workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make sure that the image exists
        run: skopeo inspect 'docker://ghcr.io/ciffelia/koe:git-${{ github.sha }}'

      - name: Setup devtools
        run: yarn install --immutable
        working-directory: ./devtools

      - name: Configure git author
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create prerelease
        run: yarn run create-prerelease
        working-directory: ./devtools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: generate-docker-tags
        run: |
          tags=$(yarn run generate-docker-tags)
          echo "$tags"
          echo "::set-output name=tags::$tags"
        working-directory: ./devtools

      - name: Create Docker tags
        run: |
          for tag in '${{ steps.generate-docker-tags.outputs.tags }}'
          do
            skopeo copy --all 'docker://ghcr.io/ciffelia/koe:git-${{ github.sha }}' "docker://ghcr.io/ciffelia/koe:$tag"
          done
